### ISSUE TITLE
Feature Request - ONTAP user management

### ISSUE THREAD

**Issue by rbenigno** [NetApp/terraform-provider-netapp-cloudmanager#141]
Working with a customer that wants to use a dedicated Ansible service account for CVO in their DevOps pipeline .  We stand up CVO with Terraform, but there is no clean way (that I can find) to create an ONTAP account.

The current workaround is to have a step where Ansible creates the ONTAP account, and the real Ansible playbooks run after that under the new account.  Would be great we could create the account as part of the Terraform build instead.

Thanks.

**Comment by lonico** [comment]
Are you using na_ontap_user with Ansible?

**Comment by rbenigno** [comment]
Yes.

```
  - name: User Accounts
    na_ontap_user:
      <<: *login
      state: "{{ item.state | default('present') }}"
      vserver: "{{ item.vserver | default(cluster.ontap_info.cluster.name) }}"
      name: "{{ item.name }}"
      application_dicts: "{{ item.application_dicts }}"
      role_name: "{{ item.role_name }}"
      set_password: "{{ item.set_password }}"
    loop: "{{ users | default([]) }}"
```
